move qdrant_openapi_client into qdrant_client.http
qdrant/qdrant_client pull request #27
Opened 2022-03-07 14:38 UTC by generall

2022-03-07 15:30 UTC, joein commented
There is an outdated import in `README.md`

2022-03-07 15:31 UTC, joein requested changes
Also there is an outdated import in `README.md`

2022-03-07 18:12 UTC, joein approved these changes

2022-03-08 02:40 UTC, monatis commented
We should also update the code snippet in readme, shouldn't we?

2022-03-08 18:39 UTC, merged